version: '3.1'

services:
     revoverflow-question-service:
         image: 'ro-question:latest'
         build:
             context: .
             dockerfile: Dockerfile
         volumes:
             - '/questionservice'
             - '/root/.m2'
         ports:
             - '8082:8082'
